name: CI/CD to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login assignment4.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build image
        run: docker build -t assignment4.azurecr.io/myapp:latest .

      - name: Push image
        run: docker push assignment4.azurecr.io/myapp:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ourwebapp1235
          images: assignment4.azurecr.io/myapp:latest

          #hello